import { dayOnePart1, dayOnePart2 } from "./dayOne";
import { dayTwoPart1, dayTwoPart2 } from "./dayTwo";
import { dayThreePart1, dayThreePart2 } from "./dayThree";
import { dayFour } from "./dayFour";
import { dayFive } from "./dayFive";

// console.log("Day 1:");
// console.log("Part 1: " + dayOnePart1());
// console.log("Part 2: " + dayOnePart2());
// console.log("Day 2:");
// console.log("Part 1: " + dayTwoPart1());
// console.log("Part 2: " + dayTwoPart2());
// console.log("Day 3:");
// console.log("Part 1: " + dayThreePart1());
// console.log("Part 2: " + dayThreePart2());
// console.log("Day 4:");
// const dayFourAnswers = dayFour();
// console.log("Part 1: " + dayFourAnswers.part1);
// console.log("Part 2: " + dayFourAnswers.part2);
console.log("Day 5:");
console.log("Part 1: " + dayFive());
